# Generated by Django 4.2.3 on 2023-07-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
