# Generated by Django 4.2.3 on 2023-07-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0003_brand'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
    ]
