# Generated by Django 4.2.3 on 2023-07-12 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0004_alter_brand_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo1', models.ImageField(upload_to='product/')),
                ('photo2', models.ImageField(upload_to='product/')),
                ('mrp', models.CharField(max_length=10)),
                ('sellingprice', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('brandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfumes.brand')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfumes.category')),
            ],
        ),
    ]
