# Generated by Django 4.2.3 on 2023-07-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('6ML', '6ML'), ('12ML', '12ML'), ('50ML', '50ML')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Perfume', 'Perfume'), ('Oriental', 'Oriental')], max_length=20),
        ),
    ]
