# Generated by Django 4.2.3 on 2023-07-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0008_feeback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feeback',
            new_name='feedback',
        ),
    ]
