# Generated by Django 4.2.3 on 2023-07-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0009_rename_feeback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('50ML', '50ML'), ('6ML 12ML', '6ML 12ML'), ('6ML', '6ML'), ('12ML', '12ML')], max_length=20),
        ),
    ]
