# Generated by Django 4.2.3 on 2023-07-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0010_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Top', 'Top'), ('All', 'All')], default='All', max_length=20),
        ),
    ]
