# Generated by Django 4.2.3 on 2023-07-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0012_product_mrp12_product_sellingprice12'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='products',
        ),
    ]
