# Generated by Django 4.2.3 on 2023-07-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(default='', upload_to='review/'),
        ),
    ]
