# Generated by Django 4.2.3 on 2023-08-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0018_products_mrp12_products_sellingprice12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='mrp12',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='sellingprice12',
            field=models.CharField(default='', max_length=10),
        ),
    ]
