# Generated by Django 4.2.3 on 2023-08-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0019_alter_products_mrp12_alter_products_sellingprice12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='mrp12',
        ),
        migrations.RemoveField(
            model_name='products',
            name='sellingprice12',
        ),
    ]
