# Generated by Django 4.2.3 on 2023-08-14 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0022_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='perfumes.products'),
        ),
    ]
