# Generated by Django 4.2.3 on 2023-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0023_alter_productsize_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(choices=[('50ML', '50ML'), ('6ML 12ML', '6ML 12ML'), ('6ML', '6ML'), ('12ML', '12ML'), ('100ML', '100ML')], max_length=20),
        ),
    ]
