from django.urls import path, include
from perfumes import views
from django. contrib.auth.views import  LoginView, LogoutView
urlpatterns = [
    path('',views.home),
    path('sbc',views.sbc),
    path('ori',views.ori),
    path('about',views.about),
    path('contact',views.contact),
    path('luxury',views.luxury),
    path('men',views.men),
    path('women',views.women),
    path('unisex',views.unisex),
    path('sbb',views.sbb),
    path('ARMANI',views.ARMANI),
    path('BURBERRY',views.BURBERRY),
    path('BVLGARI',views.BVLGARI),
    path('ck',views.ck),
    path('CAROLINA',views.CAROLINA),
    path('CHANEL',views.CHANEL),
    path('CREED',views.CREED),
    path('dior',views.dior),
    path('DG',views.DG),
    path('GIVENCHY',views.GIVENCHY),
    path('product/<int:id>',views.viewproduct),
    path('issey',views.issey),
    path('jaguar',views.jaguar),
    path('maison',views.maison),
    path('mont',views.mont),
    path('paco',views.paco),
    path('roja',views.roja),
    path('tomford',views.tomford),
    path('versace',views.versace),
    path('victoria',views.victoria),
    path('yves',views.yves),
    path('zara',views.zara),
    path('david',views.david),
    path('boss',views.boss),
    path('guess',views.guess),
    path('lacoste',views.lacoste),
    path('tommy',views.tommy),
    path('ferrari',views.ferrari),
    path('prada',views.prada),
    path('drakkar',views.drakkar),
    path('terre',views.terre),
    path('thank',views.thank),
    path('insertcontact',views.insertcontact),
    path('insertreview',views.insertreview),
    path('productdetail/<int:id>/<int:bid>',views.productdetail),
    path('FAQ',views.FAQ),
    path('search',views.search),
    path('COU',views.COU),
    path('term',views.term),
    path('feedback',views.feedback),

path('login/',LoginView.as_view(), name= 'login'),
path('logout/',LogoutView.as_view(), name= 'logout'),
path('sign/',views.sign),




]