# Generated by Django 4.2.3 on 2023-08-21 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0023_alter_productsize_productid'),
        ('orders', '0002_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='perfumes.productsize'),
        ),
    ]
